# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/favicon.png"
    high_res_favicon: "/img/favicon.png" # 高清 favicon
    apple_touch_icon: "/img/favicon.png" #  iOS 主屏按钮图标
    keywords: "楚韵江南 个人博客" # 网站关键词
    site_verification:
        google:
        baidu:

    # Enable generate structured-data as JSON+LD for SEO or not.
    #        Set as 'false' if it cause some wrong when `hexo g`.
    structured_data: true

# Jump Links Settings
url:
    rss: atom.xml # 设置生成的 rss 或 atom url
    daily_pic: "#" # 设置 daily_pic 模块 跳转 url
    logo: "#" # 设置 logo 的跳转 ur


# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Schemes
#scheme: Nexus
scheme: Paradox
#scheme: Isolation

# UI & UX: slogan, color, effect
uiux:
    slogan:
         - "深自缄默，如云漂泊"
         - " "
         - "YOU’VE MADE A BRAVE DECISION, WELCOME."
    theme_color: "#0097A7"
    theme_sub_color: "#00838F"
    hyperlink_color: "#00838F"
    button_color: "#757575"
    android_chrome_color: "#0097A7"
    nprogress_color: "#29d"
    nprogress_buffer: "800"

# JS Effect Switches 用来控制 Material 主题中自带的多种 js 特性
js_effect:
    fade: true # 页面加载时部分模块的渐显效果。默认为 true
    smoothscroll: fal # 页面平滑滚动特效。默认为 false

# Reading experience 用于设置阅读体验
reading:
    entry_excerpt: 80 # 首页文章输出摘要的字符长度。默认为80

# Thumbnail Settings 用于设置文章缩略图相关
thumbnail:
    purecolor: # 填入颜色代码。如果文章内无设置缩略图，此项又不为空，则使用纯色缩略图
    random_amount: 19 # 随机图片数量，根据 主题文件夹 -> source -> img -> random 中的图片数量设置

# Background Settings 用于设置站点背景
# bing available parameter:
#     new | color= | type=
#         color available value: black, blue, brown, green, multi, orange, pink, purple, red, white, yellow
#         type available value: A (animal), C (culture), N (nature), S (space), T (travel)
background:
    purecolor: "#F5F5F5" # 填入颜色代码。则站点使用纯色背景
    #bgimg: "/img/bg.png" # 背景地址，默认调用 主题文件夹 -> source -> img 中的 bg.png。可更换此图片或者自己填入 url
    bing: # 用于启用 bing 图片 https://material.viosey.com/intro/ ==>详情
        enable: false
        parameter:

# Images Settings 用于设置站点图片
img:
    logo: "/img/logo.png" # 显示于 blog_info 模块中
    avatar: "/img/avatar.png" # 你的头像设置
    daily_pic: "/img/daily_pic.png" # 显示于 daily_pic 模块中
    sidebar_header: "/img/sidebar_header.png" # 显示于 sidebar 顶部
    footerico: "/img/footer/footer_ico-" # 设置 footer 中 SNS 图标的路径
    random_thumbnail: "/img/random/material-" # 随机缩略图的路径
    footer_image: # 你可以在侧边栏底部放置任何你想要的图片
        aoyue_logo:
            link: "http://aoyue.coding.me/"
            src: "/image/otherSite/silder/upyun_logo.png"
        chuyun_logo:
            link: "http://chuyun.github.io"
            src: "/image/otherSite/silder/chuyun_logo.png"

# Custom Fonts
#   family: the font-family which will be used in the theme
#   host: uri of fonts host.
#       Available value of "host": google | baomitu | ustc | custom
fonts:
    family: Roboto, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", Arial, sans-serif
    use: google
    custom_font_host:

# Card Elevation Level 用于设置文章列表的卡片阴影，如无特殊要求 无需额外修改
card_elevation: 2

# Copyright
# Specify the date when the site was setup.
#   For example, if you set it as 2015, then footer will show '© 2015 - 2017'
copyright_since:

# Qrcode for redirect at other device
#   use: choose which method to generate the qrcode for each posts.
#       Available value of "use": plugin | online
#           - When use "plugin", you need to install the hexo-helper-qrcode.
#           - When use "online", the qrcode will be generated by 'pan.baidu.com' in China.
qrcode:
    enable: false
    use: plugin


# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# TOC Button

toc:
#   use: choose whether the line_number of toc will show or not.
#       Available value of "linenumber": true | false
    linenumber: true
# SNS Menu 用于填写你的 SNS 信息，除了 email，其他信息会以按钮的形式显示在 footer
# SNS Menu
sns:
    email: info_together@aliyun.com
    facebook: "https://www.facebook.com/xi.ling.946"
    twitter: # "https://twitter.com/twitter"
    googleplus: "https://www.google.com/u/0/110128836825993362445"
    weibo: "http://weibo.com/3948040744"
    instagram:
    tumblr:
    github: "http://github.com/chuyun/"
    linkedin:
    zhihu:
    bilibili:
    telegram: #"@ChuYun"

# SNS Share Switch 用于定义分享菜单中的项目， false 的项将不会显示在分享菜单中
sns_share:
    twitter: true
    facebook: true
    googleplus: true
    weibo: true
    linkedin: false
    qq: true
    telegram: true

# Sidebar Customize
sidebar:
    dropdown:
        Email Me:
            link: "mailto:info_togetheraliyun" # 参数为相对路径，对应 hexo 目录下的 source 文件夹内的相应文件夹
            icon: email   # 参数为自定义的 Material 图标，可用图标可在 https://material.io/icons/ 查询
        Sina Weibo:
            link: "http://weibo.com/3948040744"
            icon:  chat
    homepage:
        use: true
        icon: home
        divider: false
    archives:
        use: true
        icon: inbox
        divider: false
    categories:
        use: false
        icon: chrome_reader_mode
        divider: true
    pages:
        关于:
          link: "/about"
          icon: person
          divider: false
        图库:
          link: "/gallery"
          icon: photo library
          divider: false
        标签云:
          link: "/tags"
          icon: bookmark
          divider: false
        留言板:
          link: "/messages"
          icon: dashboard
          divider: false
        友情链接:
          link: "/links"
          icon: people
          divider: true
        ReadMe:
          link: "/aboutSite"
          icon:
          divider: false
        社会公益:
          link: "/benefit"
          icon:
          divider: false
        知识共享协议:
          link: "/agreement"
          icon:
          divider: true
        #About:
            #link: "/about"
            #icon: person
            #divider: false
    article_num:
        use: true # 设置成 true 时会在侧边栏显示文章总数
        divider: false
    footer:
        divider: true # 设置成 true 后会在侧边栏底部之前增加一条分割线
        theme: false # 设置成 true 后会在侧边栏底部增加一个指向 Material 主题的链接
        support: false
        feedback: false
        material: false


# ---------------------------------------------------------------
# Integrated Services
# ---------------------------------------------------------------

# MaterialCDN
# When you set 'use' as true, the needed css, js, font file will have a new src.
# The new src will have the base domain you configured in 'base'.

materialcdn:
    use: 
    base: 

# Comment Systems
# Available value of "use":
#     disqus | disqus_click | changyan | 163gentie
comment:
    use: disqus_click
    shortname: chuyun
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path
    gentie_productKey: "0d21bef2835b4f7e97c50a3f8e912afd"

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: local
    swiftype_key:

# Analytics Systems
# Available value:
#     baidu | google | cnzz
analytics:
    use:
    site_id:

# Leancloud Views
leancloud:
    enable: false
    app_id: #你的 app_id
    app_key: #你的 app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: true
    all_site_uv: true # 可统计全站的独立访客人数，即可在 blog_info 模块的 Menu 菜单中看到
    post_pv: true # 统计每篇文章的页面浏览次数，在文章页的 分享按钮 菜单中可看到
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"
